In [1]:
# 라이브러리 로드 
import pandas as pd

In [ ]:
# 라이브러리 설치
# !pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# 1차원 데이터 형인 Series 생성
# Series는 pandas에서 제공하는 데이터의 형태 

pd_series = pd.Series(
    [1000, 2000, 3000, 4000]
)

In [4]:
print(pd_series)

0    1000
1    2000
2    3000
3    4000
dtype: int64


In [5]:
print(type(pd_series))

<class 'pandas.core.series.Series'>


In [6]:
print(pd_series[2])

3000


In [9]:
# Series에 index를 추가하여 생성
# data의 개수와 index의 개수는 같게 생성
# 같지 않다면 -> 에러 발생생
pd_series2 = pd.Series(
    [5000, 6000, 6000, 6500], 
    index = ['아메리카노', '카페라떼', '카푸치노', '카페모카']
)

In [10]:
print(pd_series2)

아메리카노    5000
카페라떼     6000
카푸치노     6000
카페모카     6500
dtype: int64


In [11]:
print(pd_series2['아메리카노'])

5000


In [12]:
print(pd_series2[0])

5000


C:\Users\moons\AppData\Local\Temp\ipykernel_18400\2512544233.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(pd_series2[0])


In [14]:
# Series class -> 변수와 함수가 존재 
# 변수 중 데이터가 저장된 변수 : values
print("Series에서 데이터는 ", pd_series2.values)

Series에서 데이터는  [5000 6000 6000 6500]


In [15]:
print(type(pd_series2.values))

<class 'numpy.ndarray'>


In [16]:
# 변수 중 index는 index 변수에 저장 
print("Series에서 index는 ", pd_series2.index)

Series에서 index는  Index(['아메리카노', '카페라떼', '카푸치노', '카페모카'], dtype='object')


In [18]:
pd_series2['아메리카노'] = 5500

In [19]:
print(pd_series2)

아메리카노    5500
카페라떼     6000
카푸치노     6000
카페모카     6500
dtype: int64


In [24]:
pd_series2.index = ['아메리카노', '카페라떼', '카푸치노','마끼아또']

In [25]:
pd_series2

아메리카노    5500
카페라떼     6000
카푸치노     6000
마끼아또     6500
dtype: int64

In [26]:
# 2차원 데이터 : 데이터프레임
# 데이터프레임은 1차원 데이터인 스리즈들을 묶음

data = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
]
pd_df = pd.DataFrame(data)

In [27]:
print(pd_df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [28]:
pd_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [33]:
pd_df[1][2] = 10

In [34]:
pd_df

0   1  2
0  1   2  3
1  4   5  6
2  7  10  9

In [35]:
print(pd_df.values)
print(pd_df.index)
print(pd_df.columns)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]
RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)


In [ ]:
# 데이터프레임에서 columns 를 변경(데이터프레임의 전체 컬럼의 이름은 변경경)
pd_df.columns = ['A', 'B', 'C']

In [38]:
pd_df

A   B  C
0  1   2  3
1  4   5  6
2  7  10  9

In [42]:
# 데이터프레임에서 특정 컬럼의 이름을 변경 
pd_df.rename(
    columns={
        'A' : 'a', 
        'C' : 'c'
    }, index={
        1 : 15
    }, inplace = True
)

In [43]:
pd_df

a   B  c
0   1   2  3
15  4   5  6
2   7  10  9

In [44]:
df = pd_df

In [45]:
df

a   B  c
0   1   2  3
15  4   5  6
2   7  10  9

In [47]:
df = df.rename(
    columns ={
        'B' : 'b'
    }
)

In [48]:
df

a   b  c
0   1   2  3
15  4   5  6
2   7  10  9

In [50]:
df2 = pd_df

In [52]:
pd_df.rename(
    index = {
        0 : 100
    }, inplace = True
)

In [53]:
pd_df

a   B  c
100  1   2  3
15   4   5  6
2    7  10  9

In [54]:
df2

a   B  c
100  1   2  3
15   4   5  6
2    7  10  9

In [59]:
# 반복문을 이용해서 여러개의 전역변수를 생성하는 방법 
# 전역변수가 저장되어 있는 공간 
# print(globals())

for i in range(5):
    # print(i)
    # 반복 실행될때 a+i가 더해진 변수명을 생성
    # a0, a1, a2, a3, a4
    # print(f"a{i}")
    globals()[f"a{i}"] = i

In [60]:
a0

0

In [61]:
a1

1

In [62]:
a2

2

In [63]:
a3

3

In [64]:
a4

4

In [65]:
# 2차원 dict, list 혼합되어있는 형태 -> 데이터프레임
data = {
    'name' : ['test1', 'test2', 'test3'], 
    'age' : [20, 30, 40]
}
df = pd.DataFrame(data)

In [66]:
df

name  age
0  test1   20
1  test2   30
2  test3   40

In [68]:
print(data.keys())
print(data.values())

dict_keys(['name', 'age'])
dict_values([['test1', 'test2', 'test3'], [20, 30, 40]])


In [74]:
data2 = [
    {'name' : 'test1', 'age' : 20}, 
    {'name' : 'test2', 'address' : 'seoul'}
]
df2 = pd.DataFrame(data2)

In [75]:
df2

name   age address
0  test1  20.0     NaN
1  test2   NaN   seoul

#### 외부의 데이터 파일을 로드 
- csv, tsv
    - pandas 안에 있는 read_csv(파일의 경로)
- json
    - pandas 안에 있는 read_json(파일의 경로)
- xml 
    - pandas 안에 있는 read_xml(파일의 경로)
- 공통적으로 사용이 되는 매개변수
    - encoding 매개변수 
        - 기본값은 'UTF-8'
        - 데이터에 한글이 포함되어 있는때 종종 에러 발생 
            - 'CP949', 'EUC-KR'로 변경을 하면 에러 X
- excel 
    - read_excel(파일의 경로)
    - encoding 매개변수가 존재하지 않는다. 